Добавлен наставник
htmlacademy-htmlcss/1125131-nerds-29 pull request #1
Opened 2020-09-11 18:25 UTC by mihaqlovm

2020-09-12 18:47 UTC, mikhin requested changes
Мне все прям очень понравилось! 👏 Очень хорошее начало! С семантикой, структурой, иерархиями ты справился очень хорошо, молодец!

2020-09-12 18:47 UTC, mikhin commented on Readme.md
> +* Наставник: [Юрий Михин](https://htmlacademy.ru/profile/undgrnd).
👍 👍 👍

2020-09-12 18:47 UTC, mikhin commented on catalog.html
> +        <nav>
Правильная семантика для навигации, класс! 🙌

2020-09-12 18:47 UTC, mikhin commented on catalog.html
> +          <a>
Нужен `href`, если `href` не удается подобрать, то скорее всего это `span`.

2020-09-12 18:47 UTC, mikhin commented on catalog.html
> +          <img src="https://via.placeholder.com/15x15" width="15" height="15" alt="Иконка корзины">
Мы будем обсуждать это позже, после следующих лекций — в вёрстке есть два понятия насчет использования изображений: контентные изображения (за которыми люди идут в интернет) и декоративные изображения (которые мы хотим использовать на наших сайтах, как дизайнеры или разработчики). Контентые изображения — это фотографии в новостях, фото в Википедии, комиксы, фотки в инстаграме — т.е. как бы сам контент. А все остальное, всякие пиктограммы, «иконки», и все вот это, что относится к дизайну — это декоративные. И в этом моменте мы должны понять, что когда мы размечаем структуру документа, т.е. пишем HTML, мы не должны хотеть знать про какое-то там оформление и про то, как его там оформляют (ходят слухи что на CSS, но это не точно). Поэтому мы не вставляем декоративные изображения в HTML 😄  Ну, сейчас, это не принципиально, можно и оставить.

2020-09-12 18:47 UTC, mikhin commented on catalog.html
> +          <input type="checkbox" name="features" checked>Слайдер
Чекбоксам нужен `value` атрибут, чтоб на сервер ушли значения отмеченных пунктов.

2020-09-12 18:47 UTC, mikhin commented on catalog.html
> +      <section>
Очень-очень-очень хорошо и правильно размечена форма, черт побери. Я бы даже сам так не разметил с первого раза в каком-нибудь рабочем проекте 👍 👍 👍 

Единственный момент — я бы сомневался насчет использования `section`, т.к. не уверен, что это прям действительно ПОДРАЗДЕЛ нашего документа. И еще точно бы сделал иначе подзаголовки `h2`, т.к. `h2` семантически имеет как бы большой вес в иерархии заголовков, а тут у нас ну просто фильтр, ну просто небольшие подзаголовки. Может `h3` более подойдет? А`h2` это будет например `Фильтр товаров`?

2020-09-12 18:47 UTC, mikhin commented on catalog.html
> +          <h2>Сортировать:</h2>
Вот тут это скорее всего не подзаголовки, а кнопки. Подзаголовки хоть и имеют приставку `под`, но все же заголовки. А значит должны озаглавливать какую-то часть документа. А если нечего озаглавливать, значит и не нужен подзаголовок. Как и в этом случае. 😄

2020-09-12 18:47 UTC, mikhin commented on catalog.html
> +          <img src="https://via.placeholder.com/11x10" alt="Иконка сортировки от большего к меньшему">
Эти кнопки — это интерактивные элементы, а значит нужен какой-то интерактивный элемент: ссылка или кнопка.

Плюс чуть выше писал про разницу контентных и декоративных изображений — это как раз тоже похожий случай.

2020-09-12 18:47 UTC, mikhin commented on catalog.html
> +                  <img src="https://via.placeholder.com/358x578" width="358" height="578" alt="Шаблон Седона">
Вот тут как раз очень хороший случай для понимания разницы разметки документа на уровне HTML и оформления CSS и дизайна макетов. HTML как бы не должен хотеть знать что там творится в CSS, а тем более и в дизайне и в макетах, потому что HTML это база в пирамиде, он не должен смотреть на все следующие уровни абстракции, которые ложатся на него (CSS и JS, например), наоборот они смотрят в него. Если мы оформляем документ, будто пишем вордовский документ или готовим структуру для прослушивания на аудио-устройствах (да, так пользуются интернетом люди с проблемами зрения) мы должны хотеть ставить подзаголовок выше его содержимого. Т.е. сначала идет `<h4>Седона</h4>`, а потом уже следом идет весь контент, который принадлежит этому заголовку.

2020-09-12 18:47 UTC, mikhin commented on catalog.html
> +                  <h4>Sedona</h4>
Я бы бахнул `span` внутри заголовка, который бы более раскрывал суть происходящего. Например ` <h4><span>Готовый шаблон туристического агентства</span> Sedona</h4>`. Тогда на уровне структуры документа контент получился бы более насыщенным.

2020-09-12 18:47 UTC, mikhin commented on catalog.html
> +              <li><img src="https://via.placeholder.com/358x578" width="358" height="578" alt="Шаблон Пинк"></li>
Давай разметим все эти пункты как и первый пункт? Это же тоже ссылки, в них тоже если цена и все такое)

2020-09-12 18:47 UTC, mikhin commented on catalog.html
> +      <section>
Чутка избыточен тут `section` 😄 Не надо бояться `div` — это достойный и вполне себе используемый тег. Другое дело, что нельзя `div` заменять семантику документа, но так ты этим и не страдаешь 👍

2020-09-12 18:47 UTC, mikhin commented on catalog.html
> +            <li><a>1</a></li>
Нужен href, если href не удается подобрать, то скорее всего это span.

2020-09-12 18:47 UTC, mikhin commented on catalog.html
> +            <li><a href="">2</a></li>
Я бы добавил `span` который пояснял бы, что значат эти загадочные числа 😄

2020-09-12 18:47 UTC, mikhin commented on index.html
> +      <h1>Дизайн-студии Нёрдс</h1>
Очень правильно использован заголовок 👍

2020-09-12 18:47 UTC, mikhin commented on index.html
> +      <section>
Если у нас тут **список** слайдов, то давай их разметим списком?)

2020-09-12 18:47 UTC, mikhin commented on index.html
> +        <h2>Что мы умеем делать</h2>
БЭНГ-БЭНГ! Клевый заголовок, так держать! 👍

2020-09-12 18:47 UTC, mikhin commented on index.html
> +            <button>Заказать</button>
Скорее всего эти элементы во всех трех карточках — это ссылки, ведущие на внутренние страницы сайта, где будут раскрыты смыслы и более подробно описаны услуги

2020-09-12 18:47 UTC, mikhin commented on index.html
> +            <img src="https://via.placeholder.com/300x146" width="300" height="146" alt="Два смартфона">
Чутка суховат `alt`, хотя и формально верно. Ты описал то, что изображено на картинке, но какой от этого смысл?) Т.е. людям с проблемами зрения, ни горячо ни холодно от такой этой фразы, которую им произнесет голосовой помощник. Да, вероятно сама картинка так себе и дизайнеру нужно бы подумать получше над тем, как описать картинками услуги студии, но и мы тоже можем сделать еще чутка лучше. Например, «Два смартфона с примерами наших приложений».

2020-09-12 18:47 UTC, mikhin commented on index.html
> +        <h4>Выполняем заказы на разработку:</h4>
По правилам русского языка в подзаголовках не может быть окончаний двоеточием или точкой. Предлагаю исправить и в этом месте не следовать макету. Такое бывает, что дизайнер ошибается и в реальной работе это повод сходить и спросить, а зачем такое сделано. Бывает, что низачем и можно сделать правильно)

2020-09-12 18:47 UTC, mikhin commented on index.html
> +          <li><img src="https://via.placeholder.com/209x90" width="209" height="90" alt="Логотип барбершопа Бородинский"></li>
А тут ведь тоже ссылки должны быть?

2020-09-13 07:28 UTC, mihaqlovm commented on catalog.html
> +          <img src="https://via.placeholder.com/15x15" width="15" height="15" alt="Иконка корзины">
Ок. Понял так: иконки будут «зашиты» в CSS, поэтому можно было не выводить их в HTML.

2020-09-13 07:42 UTC, mihaqlovm commented on catalog.html
> +          <img src="https://via.placeholder.com/11x10" alt="Иконка сортировки от большего к меньшему">
Резонно )) Поставил кнопки. Но пока не приступили к CSS оставлю изображения. Мне потом будет проще понять что к чему.

2020-09-13 07:53 UTC, mihaqlovm commented on catalog.html
> +                  <img src="https://via.placeholder.com/358x578" width="358" height="578" alt="Шаблон Седона">
Ок, понял. Руководствовался следующей логикой: заголовок, описание, кнопка появляются когда пользователь наводит на изображение, а значит сперва нужно поставить картинку, потому что она появляется первой...

2020-09-13 07:59 UTC, mihaqlovm commented on catalog.html
> +                  <h4>Sedona</h4>
Не догнал. В макете этого текста нет. То есть получается, что мы сами можем для улучшения «считывания» дописывать текст? Но тогда может «поехать» вёрстка — больше символом в <H4>. Или же мы не будем выводить на экран текст в <span>?

2020-09-13 08:01 UTC, mihaqlovm commented on catalog.html
> +              <li><img src="https://via.placeholder.com/358x578" width="358" height="578" alt="Шаблон Пинк"></li>
Давай )) Просто оставить теги пустыми (H4, p, button)?

2020-09-13 08:04 UTC, mihaqlovm commented on catalog.html
> +            <li><a>1</a></li>
Почему нельзя a без href? Я же не могу ссылаться с этой страницы на саму себя или ничего страшного в этом нет? А если span, то как потом он будет «перемещаться» когда мы окажемся на второй (и т. д.) странице пагинации?

2020-09-13 08:04 UTC, mihaqlovm commented on catalog.html
> +            <li><a href="">2</a></li>
Покажи, пожалуйста, пример. Не совсем понимаю как и зачем.

2020-09-13 08:09 UTC, mihaqlovm commented on index.html
> +            <button>Заказать</button>
Ок. Но неоднозначно. Лучше уточнить у дизайнера. Есть же вероятность, что маркетолог поставил ему задачу сделать поп-ап с формой обратного звонка ))

2020-09-13 08:11 UTC, mihaqlovm commented on index.html
> +            <img src="https://via.placeholder.com/300x146" width="300" height="146" alt="Два смартфона">
Согласен, дизайнеру надо дать по башке )) Но, если ты не сильно настаиваешь, оставлю тут alt как есть — лениво менять ))

2020-09-13 21:04 UTC, mikhin commented on catalog.html
> +          <img src="https://via.placeholder.com/15x15" width="15" height="15" alt="Иконка корзины">
Верно!

2020-09-13 21:05 UTC, mikhin commented on index.html
> +            <button>Заказать</button>
Верно, согласен!

2020-09-13 21:05 UTC, mikhin commented on index.html
> +            <img src="https://via.placeholder.com/300x146" width="300" height="146" alt="Два смартфона">
Не настаиваю)

2020-09-13 21:08 UTC, mikhin commented on catalog.html
> +                  <img src="https://via.placeholder.com/358x578" width="358" height="578" alt="Шаблон Седона">
Не, смотри, прикол в том, что че там происходит в дизайне и что там пользователь видит первым нам не очень интересно, потому что HTML должен хотеть быть не про это. HTML должен хотеть быть про правильную структуру и разметку в документе. Т.е. мы не должны в книжках ставить части контента выше заголовка, потому что это будет сбивать читателя с толку.

К этому всему присоединяется трюк из flex в CSS — где мы можем менять визуальный порядок элементов как хотим. Поэтому клево писать HTML структурно правильно, а через CSS менять дизайн порядок и вообще стилизовать по дизайну в макетах.

2020-09-13 21:10 UTC, mikhin commented on catalog.html
> +                  <h4>Sedona</h4>
Да, мы же, верстальщики, единственные, кто отвечает за клевый HTML, поэтому глядя на дизайн мы должны сразу смотреть как представить этот документ на уровне HTML наиболее обогащенным образом. Поэтому мы можем дописывать всякие скрытые заголовоки, скрывая их «доступно» в CSS.

2020-09-13 21:10 UTC, mikhin commented on catalog.html
> +              <li><img src="https://via.placeholder.com/358x578" width="358" height="578" alt="Шаблон Пинк"></li>
Не, давай придумаем чо там за данные могут быть)

2020-09-13 21:14 UTC, mikhin commented on catalog.html
> +            <li><a>1</a></li>
Академия, да, как бы в рамках курса объясняет и позволяет оставлять пустую ссылку без href, поэтому мы можем договориться что это ОК.

Но лично мое мнение, что это не совсем ОК, т.к. непонятно зачем такое делать и зачем мы такое хотим, какая выгода у такого трюка? У меня на работе мы так никогда не делаем. Если мы хотим что-то строчное у чего нет признаков «ссылочности», то почему бы не использовать span? 

Как это будет перемещаться это не вопрос верстки, а вопрос того как верстка приходит в браузер. Если генерация HTML происходит на стороне сервера, то бэкенд-программисты обогащают верстку циклами и условиями делая статичную верстку динамичной. Пример псевдокода на PHP:

```
<li class="menu__item <?= $isCurrentItem ? "menu__item_current" : null ?>"><a>1</a></li>
```

2020-09-13 21:18 UTC, mikhin commented on catalog.html
> +            <li><a href="">2</a></li>
Я возможно чутка перебарщиваю и лезу туда, куда можно и не лезть, но просто вижу, что у тебя хороший уровень понимания происходящего, поэтому непроизвольно хочется подкинуть и рассказать каких-то фишечек)

В соседнем вопросе ответил про то, что мы можем дописывать и обогащать HTML, чтобы делать его понятнее и скрывать на уровне CSS части, которых нет в макете. Тут тоже самое: пишем, что это не просто цифры, а номера страниц:

```html
<ul>
  <li><span>Страница пагинации номер</span> <a>1</a></li>
</ul>
``` 

Не настаиваю на этом моменте, сейчас это вообще необязательно)

Еще кстати можно вот так, 

```html
<ul>
  <li><a aria-label="Страница пагинации № 1">1</a></li>
</ul>
``` 

Но это будет в лекции про доступность)

2020-09-14 07:06 UTC, mihaqlovm commented on catalog.html
> +            <li><a href="">2</a></li>
> Я возможно чутка перебарщиваю и лезу туда, куда можно и не лезть
Не, наоборот, оч. круто. Прочитал про aria-label — огонь!

2020-09-14 07:48 UTC, merged