Оживляем интерактивные элементы
htmlacademy-htmlcss/1125131-nerds-29 pull request #11
Opened 2020-10-18 13:34 UTC by mihaqlovm

Модальное окно обратной связи

2020-10-18 13:44 UTC, mikhin requested changes

2020-10-18 13:44 UTC, mikhin commented on js/script.js
> +const buttonMail = document.querySelector (".button-contact");
Пробел между вызовом функции и передачей аргументов в скобках не нужен

2020-10-18 13:44 UTC, mikhin commented on js/script.js
> +  modalClose.addEventListener("click", function (evt) {
Все эти обработчики не должны добавлять в рамках `buttonMail.addEventListener`, а должны добавлять отдельно каждый

2020-10-18 13:44 UTC, mikhin commented on js/script.js
> +    if (!modalEmail.value || !modalComment.value) {
А в макетах есть состояния ошибок при отправке?

2020-10-18 13:44 UTC, mikhin commented on js/script.js
> +      if (modal.classList.contains("modal-show")) {
Можно объединить оба условая, чтоб if один убрать и чтоб вложенность была поменьше)

2020-10-18 13:44 UTC, mikhin commented on js/script.js
> +    modalName.focus();
А реализацию с localStorage хочешь запилить?)

2020-10-18 14:25 UTC, mihaqlovm commented on js/script.js
> +  modalClose.addEventListener("click", function (evt) {
Не понял.

2020-10-18 14:26 UTC, mihaqlovm commented on js/script.js
> +    if (!modalEmail.value || !modalComment.value) {
В стайлгайде есть невалидное значение: 
![image](https://user-images.githubusercontent.com/71141692/96370590-0b128980-1167-11eb-90b0-a9e13351b337.png)

2020-10-19 07:19 UTC, mikhin commented on js/script.js
> +    if (!modalEmail.value || !modalComment.value) {
@mihaqlovm, давай это тоже оживим?)

2020-10-21 21:50 UTC, mikhin commented on js/script.js
> +let storageFormEmal = "";
Если не используется, то нужно удалить)

2020-10-21 21:50 UTC, mikhin commented on js/script.js
> +form.addEventListener("submit", function (evt) {
По аналогии лучше бы сделать отдельной функции и просто указать ссылку на нее в обработчике

2020-10-21 21:51 UTC, merged

2020-10-22 05:24 UTC, mihaqlovm commented on js/script.js
> +let storageFormEmal = "";
Не понял. Вроде бы использую.

2020-10-22 05:26 UTC, mihaqlovm commented on js/script.js
> +form.addEventListener("submit", function (evt) {
Понял. Сделал.