Декоративные элементы на внутренней странице
htmlacademy-htmlcss/1125131-nerds-29 pull request #13
Opened 2020-10-24 10:27 UTC by mihaqlovm

2020-10-24 17:31 UTC, mikhin requested changes

2020-10-24 17:31 UTC, mikhin commented on catalog.html
> +                  <div class="bar" style="width: 64%; margin-left: 6%"></div>
Давай все стили унесем в CSS)

2020-10-24 17:31 UTC, mikhin commented on catalog.html
> +            <label class="filters__label_grid"><p class="filters__text">Адаптивная</p>
По БЭМ класс-модификатор не может использоваться без основного класса)

2020-10-24 17:31 UTC, mikhin commented on catalog.html
> +            <label class="filters__label_grid"><p class="filters__text">Адаптивная</p>
Проверишь на этот счет все страницы?

2020-10-24 17:31 UTC, mikhin commented on catalog.html
> +              <button class="button-none" type="button"><img src="img/icon/icon-down-dir.svg" alt="Сортируем от большего к меньшему"></button>
Давай иконки унесем в CSS, т.к. это декор?

2020-10-24 17:31 UTC, mikhin commented on catalog.html
> +            <li class="pagination__item"><a class="pagination__link" href="#" aria-label="Страница пагинации № 2">2</a>
Можно и без aria-label — просто текст написать в ссылке и скрыть его в CSS)

2020-10-24 17:31 UTC, mikhin commented on catalog.html
> +          rows="5"></textarea>
Давай размер задавать через CSS)

2020-10-24 17:31 UTC, mikhin commented on css/style.css
> +.button-red_text-white {
Для модификатора `text_white` тут описано слишком много, не?)

2020-10-24 17:31 UTC, mikhin commented on css/style.css
> +    margin-bottom: 13px;
По БЭМ не может иметь margin. Можем забить, а можем и сделать ваще по красоте)

2020-10-24 17:31 UTC, mikhin commented on css/style.css
> +
Лишняя строка)

2020-10-24 17:31 UTC, mikhin commented on css/style.css
> +.filters__label_grid input:checked~.filters__decor_radio:after {
Давай вместо селектора тега использовать класс

2020-10-24 17:31 UTC, mikhin commented on css/style.css
> +.filters__label_grid input:checked~.filters__decor_radio:after {
Давай `~` отобьем пробелами)

2020-10-24 17:31 UTC, mikhin commented on css/style.css
> +    opacity: 0.12;
Странное число)

2020-10-24 17:38 UTC, mikhin commented
<img width="650" alt="Снимок экрана 2020-10-24 в 20 37 54" src="https://user-images.githubusercontent.com/38258318/97088339-d015c780-1638-11eb-8137-1028bd1e00a6.png">

Странно выглядит чек-бокс)

2020-10-24 17:39 UTC, mikhin commented on catalog.html
> +          <li class="catalog__item">
Где-то тут должна быть ссылка, потому что карточка товара это всегда ссылка)

2020-10-24 17:40 UTC, mikhin commented
<img width="567" alt="Снимок экрана 2020-10-24 в 20 39 44" src="https://user-images.githubusercontent.com/38258318/97088385-166b2680-1639-11eb-863d-52a9c5dc106b.png">

Кажется, что точка не совсем по центру)

2020-10-24 17:41 UTC, mikhin commented on css/style.css
> +    box-shadow: inset 0px 3px 0px rgba(0, 1, 1, 0.1);
Всегда когда 0, px не нужно)

2020-10-24 17:42 UTC, mikhin commented
https://validator.w3.org/nu/#textarea

По валидатору есть ошибки на обеих страницах

2020-10-26 16:18 UTC, mihaqlovm commented on catalog.html
> +            <label class="filters__label_grid"><p class="filters__text">Адаптивная</p>
Проверю. Но после того как закрою всю домашку.

2020-10-26 16:18 UTC, mihaqlovm commented on catalog.html
> +              <button class="button-none" type="button"><img src="img/icon/icon-down-dir.svg" alt="Сортируем от большего к меньшему"></button>
А если оставить вот так:
`              <button class="button-none" type="button">
                <svg aria-label="Сортируем от меньшего к большему" width="11" height="10" viewBox="0 0 11 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <g opacity="0.2">
                  <path d="M5.5 0L0 10H11L5.5 0Z" fill="#A6A6A6"/>
                  </g>
                  </svg>
              </button>`
?

2020-10-26 16:19 UTC, mihaqlovm commented on catalog.html
> +            <li class="pagination__item"><a class="pagination__link" href="#" aria-label="Страница пагинации № 2">2</a>
Не против если оставлю с aria-label?

2020-10-26 16:21 UTC, mihaqlovm commented on catalog.html
> +          rows="5"></textarea>
Ок

2020-10-26 16:24 UTC, mihaqlovm commented on css/style.css
> +.button-red_text-white {
Пожалуй.

2020-10-26 16:25 UTC, mihaqlovm commented on css/style.css
> +    margin-bottom: 13px;
Что не может иметь марджин?

2020-10-26 16:26 UTC, mihaqlovm commented on css/style.css
> +.filters__label_grid input:checked~.filters__decor_radio:after {
Почему?

2020-10-26 16:28 UTC, mihaqlovm commented on css/style.css
> +
> <img alt="Снимок экрана 2020-10-24 в 20 37 54" width="650" src="https://user-images.githubusercontent.com/38258318/97088339-d015c780-1638-11eb-8137-1028bd1e00a6.png">
> 
> Странно выглядит чек-бокс)

Не знаю как победить, используя свг. А нарисовать со скруглениями и разрывом в углу не могу.

2020-10-26 16:35 UTC, mihaqlovm commented on catalog.html
> +          <li class="catalog__item">
Почему всегда? Навёл на картинку, появилась модалка с кнопкой, а на ней уже ссылка.

2020-10-26 16:37 UTC, mihaqlovm commented
> <img alt="Снимок экрана 2020-10-24 в 20 39 44" width="567" src="https://user-images.githubusercontent.com/38258318/97088385-166b2680-1639-11eb-863d-52a9c5dc106b.png">
> 
> Кажется, что точка не совсем по центру)

Не знаю как победить. У меня вот так:
```
    top: 50%;
    left: 50%;
```

2020-10-27 11:21 UTC, mikhin commented on catalog.html
> +            <li class="pagination__item"><a class="pagination__link" href="#" aria-label="Страница пагинации № 2">2</a>
Не против)

2020-10-29 18:23 UTC, merged